version: '3.8'

services:
  db_patients:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - network

  patients-bot:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db_patients
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres-data: